### PR TITLE
Add translation JSON for the Japanese locale

### PR DESCRIPTION
**Pull request by kitsunenokenja**
This initial translation file isn't fully completed, and some translations may not be absolutely perfect, but this should be a good start for Japanese support.

この翻訳は未完全であり、様々な項目が完璧ではないかもしれませんが、これは適当な開始だと思われています。

### CODE REVIEW

**Comment by Eitot** [comment]
@kitsunenokenja: the locale files have been updated for version 3. You might want to check your translations again. :-)

https://github.com/ProtonMail/WebClient/tree/v3/src/assets/locales

**Comment by jasonstockman** [comment]
We keep adding new translation keys. I will update the English file which has all the keys (as of today) so please use that as your reference.

**Comment by jasonstockman** [comment]
@kitsunenokenja The latest translation file is here:
https://github.com/ProtonMail/WebClient/blob/v3/src/assets/locales/en_US.json

Can you update with all of the translation keys?

**Comment by kitsunenokenja** [comment]
@jasonstockman OK, I'll post more token translations when I have a chance.

**Pull request merged**
