### PR TITLE
Fixed wrong case in JS Vendor filepaths

### PR DESCRIPTION
**Pull request by pidov**
Fixed wrong paths (casing), preventing UNIX systems from running the grunt task (```grunt --prod```). Errors below: 

```
Running "copy:build_vendorjs" (copy) task
Warning: Unable to read "vendor/DOMPurify/purify.js" file (Error code: ENOENT). Use --force to continue.
Running "copy:build_vendorjs" (copy) task
Warning: Unable to read "vendor/showdown/compressed/showdown.js" file (Error code: ENOENT). Use --force to continue.
```

protonmail-path-error

### CODE REVIEW

**Comment by SnDer** [comment]
How did you fix this?

**Comment by SnDer** [comment]
Great job!

**Comment by jasonstockman** [comment]
Nice, I didn't realize this was case insensitive.

**Comment by bartbutler** [comment]
Depends on the filesystem. Unix tends to be case sensitive, OSX is not by
default.

**Pull request merged**
